[package]
name = "app"
default-run = "app"
version = "1.0.2"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.1.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.4", features = ["api-all", "system-tray", "updater"] }
windows = { version = "0.44", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_ProcessStatus", "Win32_System_Threading", "Win32_UI_Shell"] }
tokio = { version = "1.25", features = ["macros", "time", "sync", "net"] }
anyhow = "1.0"
widestring = "1.0"
directories = "4.0"
reqwest = "0.11"
chrono = { version = "0.4", features = ["serde"] }
raw-window-handle = "0.5"
async-trait = "0.1"
itertools = "0.10"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
strip = true
